name: Release - Test, Build & Redeploy

on:
  push:
    branches:
      - 'sandbox'

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO

  deploy:
    runs-on: ubuntu-latest
    needs: [docker]
    env:
      CONTAINER_NAME: sandbox-alami
      INTERNAL_PORT: 8888
      PUBLISHED_PORT: 8888
      PUBLISHED_PORT_BAK: 8888
    steps:
      - name: running docker info
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_IP_PUBLIC }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cat ~/.ssh/id_rsa
            echo "hello world"
            cd $HOME
            ./hello.sh
            sudo docker run -dit --name alamisharia -p 8888:8888 rizkyramadhanch/alamisharia-helloproject